---
# tasks file for config_vlan_netconf
- name: Deplay the template on Certain devices
  template:
    src: vlan.j2
    dest: "roles/config_vlan_netconf/files/vlan.xml"
- name: netcong task
  netconf_config:
    content: lookup("file", "./vlan.vml")
    
