---
- name: running the playbook
  hosts: access
  connection: network_cli
  gather_facts: False
  become: yes
  become_method: enable
  roles:
    - nxos_vlan
- name: running the playbook
  hosts: onedevice
  connection: netconf
  gather_facts: False
  become: yes
  become_method: enable
  roles:
    - config_vlan_netconf
  tags:
    - netconf
