portchannel:
  - interfaces:
      - Ethernet1/3
      - Ethernet1/7
    group: "3{{inventory_hostname[-1]}}"

  - interfaces:
      - Ethernet1/4
      - Ethernet1/8
    group: "4{{inventory_hostname[-1]}}"


  - interfaces:
      - Ethernet1/5
      - Ethernet1/6
    group: 56
