---
# tasks file for ospf
- name: configure EIGRP
  with_items: "{{eigrp.networks}}"
  debug: 
    msg: "{{item.network}}"
- name: distribute loopback under eigrp
  with_items: "{{eigrp.networks}}"
  ios_config:
    lines:
      - "network {{item.network}} {{item.wildmask}}"
    parents: router eigrp 1
