
L3_interfaces:
  - interface_type: Loopback
    interface_id: 0
    ip_address: 150.1.4.4
    subnet_mask: 255.255.255.0
      
    
  - interface_type: FastEthernet
    interface_id: 0/0
    ip_address: 155.1.47.4
    subnet_mask: 255.255.255.0


  - interface_type: Serial
    interface_id: 1/0
    ip_address: 155.1.34.4
    subnet_mask: 255.255.255.0

  - interface_type: serial
    interface_id: 1/1
    ip_address: 155.1.49.4
    subnet_mask: 255.255.255.0
