- ios_bgp:
    config:
      bgp_as: 300
      router_id: 9.9.9.9
      neighbors:
              - neighbor: 150.1.3.3
                remote_as: 300
                update_source: loopback 0
         
              - neighbor: 150.1.7.7
                remote_as: 300
                update_source: loopback 0
         
        
