  - ios_config:
      lines:
        - ip address 192.168.1.1 255.255.255.0
        - tunnel source FastEthernet 0/0
        - tunnel mode gre multipoint
        - ip nhrp network-id 11
      parents: interface tunnel 0

        
